# Generated by Django 4.1 on 2022-08-23 10:14

import datetime
import django.core.validators
from django.db import migrations, models
import selfstudy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ev_halkı',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=32, verbose_name='Soyad')),
                ('age', models.IntegerField(verbose_name='Yaş')),
                ('birth_year', models.IntegerField(default=datetime.date(2022, 8, 23), validators=[django.core.validators.MinValueValidator(1933), selfstudy.models.max_value_current_year], verbose_name='Doğum yılı')),
            ],
        ),
    ]
