# Generated by Django 4.1 on 2022-08-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0002_alter_ev_halkı_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev_halkı',
            name='birth_year',
            field=models.IntegerField(verbose_name='Doğum yılı'),
        ),
    ]
