# Generated by Django 4.1 on 2022-08-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0003_alter_ev_halkı_birth_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ev_halkı',
            options={'ordering': ['age']},
        ),
    ]
